### ISSUE TITLE
flaky test ModuleEnvironmentWatcherTest

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/gestalt#108]
org.terasology.gestalt.assets.module.autoreload.ModuleEnvironmentWatcherTest.test()

It sometimes passes, and sometimes on CI it does not
```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
	at org.terasology.gestalt.assets.module.autoreload.ModuleEnvironmentWatcherTest.test(ModuleEnvironmentWatcherTest.java:91)
```

https://github.com/MovingBlocks/gestalt/blob/a7968fe2f0308ac8890f642dc24dce16bda174ea/gestalt-asset-core/src/test/java/org/terasology/gestalt/assets/module/autoreload/ModuleEnvironmentWatcherTest.java#L84-L98

**Comment by soloturn** [comment]
still fails from time to time.

**Comment by soloturn** [comment]
Closing - fixed by #173 (also carried into #174's JUnit 6 migration branch, since that branch hit the same flake independently). Root cause: `ModuleEnvironmentWatcher.checkForChanges()` does a single non-blocking `WatchService.poll()`; the OS delivers file events asynchronously, so a change made just before calling it can still be in flight and miss that one poll. Fixed by retrying for up to 5s instead of asserting on a single poll.

(Note: I filed #172 for this same flake before spotting that this issue already existed - duplicate, closing that one too.)
